#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
:*?C:&Aacute;::Á
:*?C:&aacute;::á
:*?C:&Abreve;::Ă
:*?C:&abreve;::ă
:*?C:&ac;::∾
:*?C:&acd;::∿
:*?C:&acE;::∾̳
:*?C:&Acirc;::Â
:*?C:&acirc;::â
:*?C:&acute;::´
:*?C:&Acy;::А
:*?C:&acy;::а
:*?C:&AElig;::Æ
:*?C:&aelig;::æ
:*?C:&af;::⁡
:*?C:&Afr;::𝔄
:*?C:&afr;::𝔞
:*?C:&Agrave;::À
:*?C:&agrave;::à
:*?C:&alefsym;::ℵ
:*?C:&aleph;::ℵ
:*?C:&Alpha;::Α
:*?C:&alpha;::α
:*?C:&Amacr;::Ā
:*?C:&amacr;::ā
:*?C:&amalg;::⨿
; :*?C:&AMP;::&
; :*?C:&amp;::&
:*?C:&And;::⩓
:*?C:&and;::∧
:*?C:&andand;::⩕
:*?C:&andd;::⩜
:*?C:&andslope;::⩘
:*?C:&andv;::⩚
:*?C:&ang;::∠
:*?C:&ange;::⦤
:*?C:&angle;::∠
:*?C:&angmsd;::∡
:*?C:&angmsdaa;::⦨
:*?C:&angmsdab;::⦩
:*?C:&angmsdac;::⦪
:*?C:&angmsdad;::⦫
:*?C:&angmsdae;::⦬
:*?C:&angmsdaf;::⦭
:*?C:&angmsdag;::⦮
:*?C:&angmsdah;::⦯
:*?C:&angrt;::∟
:*?C:&angrtvb;::⊾
:*?C:&angrtvbd;::⦝
:*?C:&angsph;::∢
:*?C:&angst;::Å
:*?C:&angzarr;::⍼
:*?C:&Aogon;::Ą
:*?C:&aogon;::ą
:*?C:&Aopf;::𝔸
:*?C:&aopf;::𝕒
:*?C:&ap;::≈
:*?C:&apacir;::⩯
:*?C:&apE;::⩰
:*?C:&ape;::≊
:*?C:&apid;::≋
:*?C:&apos;::
:*?C:&ApplyFunction;::⁡
:*?C:&approx;::≈
:*?C:&approxeq;::≊
:*?C:&Aring;::Å
:*?C:&aring;::å
:*?C:&Ascr;::𝒜
:*?C:&ascr;::𝒶
:*?C:&Assign;::≔
:*?C:&ast;::*
:*?C:&asymp;::≈
:*?C:&asympeq;::≍
:*?C:&Atilde;::Ã
:*?C:&atilde;::ã
:*?C:&Auml;::Ä
:*?C:&auml;::ä
:*?C:&awconint;::∳
:*?C:&awint;::⨑
:*?C:&backcong;::≌
:*?C:&backepsilon;::϶
:*?C:&backprime;::‵
:*?C:&backsim;::∽
:*?C:&backsimeq;::⋍
:*?C:&Backslash;::∖
:*?C:&Barv;::⫧
:*?C:&barvee;::⊽
:*?C:&Barwed;::⌆
:*?C:&barwed;::⌅
:*?C:&barwedge;::⌅
:*?C:&bbrk;::⎵
:*?C:&bbrktbrk;::⎶
:*?C:&bcong;::≌
:*?C:&Bcy;::Б
:*?C:&bcy;::б
:*?C:&bdquo;::„
:*?C:&becaus;::∵
:*?C:&Because;::∵
:*?C:&because;::∵
:*?C:&bemptyv;::⦰
:*?C:&bepsi;::϶
:*?C:&bernou;::ℬ
:*?C:&Bernoullis;::ℬ
:*?C:&Beta;::Β
:*?C:&beta;::β
:*?C:&beth;::ℶ
:*?C:&between;::≬
:*?C:&Bfr;::𝔅
:*?C:&bfr;::𝔟
:*?C:&bigcap;::⋂
:*?C:&bigcirc;::◯
:*?C:&bigcup;::⋃
:*?C:&bigodot;::⨀
:*?C:&bigoplus;::⨁
:*?C:&bigotimes;::⨂
:*?C:&bigsqcup;::⨆
:*?C:&bigstar;::★
:*?C:&bigtriangledown;::▽
:*?C:&bigtriangleup;::△
:*?C:&biguplus;::⨄
:*?C:&bigvee;::⋁
:*?C:&bigwedge;::⋀
:*?C:&bkarow;::⤍
:*?C:&blacklozenge;::⧫
:*?C:&blacksquare;::▪
:*?C:&blacktriangle;::▴
:*?C:&blacktriangledown;::▾
:*?C:&blacktriangleleft;::◂
:*?C:&blacktriangleright;::▸
:*?C:&blank;::␣
:*?C:&blk12;::▒
:*?C:&blk14;::░
:*?C:&blk34;::▓
:*?C:&block;::█
:*?C:&bne;::&ERROR!
:*?C:&bnequiv;::≡⃥
:*?C:&bNot;::⫭
:*?C:&bnot;::⌐
:*?C:&Bopf;::𝔹
:*?C:&bopf;::𝕓
:*?C:&bot;::⊥
:*?C:&bottom;::⊥
:*?C:&bowtie;::⋈
:*?C:&boxbox;::⧉
:*?C:&boxDL;::╗
:*?C:&boxDl;::╖
:*?C:&boxdL;::╕
:*?C:&boxdl;::┐
:*?C:&boxDR;::╔
:*?C:&boxDr;::╓
:*?C:&boxdR;::╒
:*?C:&boxdr;::┌
:*?C:&boxH;::═
:*?C:&boxh;::─
:*?C:&boxHD;::╦
:*?C:&boxHd;::╤
:*?C:&boxhD;::╥
:*?C:&boxhd;::┬
:*?C:&boxHU;::╩
:*?C:&boxHu;::╧
:*?C:&boxhU;::╨
:*?C:&boxhu;::┴
:*?C:&boxminus;::⊟
:*?C:&boxplus;::⊞
:*?C:&boxtimes;::⊠
:*?C:&boxUL;::╝
:*?C:&boxUl;::╜
:*?C:&boxuL;::╛
:*?C:&boxul;::┘
:*?C:&boxUR;::╚
:*?C:&boxUr;::╙
:*?C:&boxuR;::╘
:*?C:&boxur;::└
:*?C:&boxV;::║
:*?C:&boxv;::│
:*?C:&boxVH;::╬
:*?C:&boxVh;::╫
:*?C:&boxvH;::╪
:*?C:&boxvh;::┼
:*?C:&boxVL;::╣
:*?C:&boxVl;::╢
:*?C:&boxvL;::╡
:*?C:&boxvl;::┤
:*?C:&boxVR;::╠
:*?C:&boxVr;::╟
:*?C:&boxvR;::╞
:*?C:&boxvr;::├
:*?C:&bprime;::‵
:*?C:&Breve;::˘
:*?C:&breve;::˘
:*?C:&brvbar;::¦
:*?C:&Bscr;::ℬ
:*?C:&bscr;::𝒷
:*?C:&bsemi;::⁏
:*?C:&bsim;::∽
:*?C:&bsime;::⋍
:*?C:&bsol;::\
:*?C:&bsolb;::⧅
:*?C:&bsolhsub;::⟈
:*?C:&bull;::•
:*?C:&bullet;::•
:*?C:&bump;::≎
:*?C:&bumpE;::⪮
:*?C:&bumpe;::≏
:*?C:&Bumpeq;::≎
:*?C:&bumpeq;::≏
:*?C:&Cacute;::Ć
:*?C:&cacute;::ć
:*?C:&Cap;::⋒
:*?C:&cap;::∩
:*?C:&capand;::⩄
:*?C:&capbrcup;::⩉
:*?C:&capcap;::⩋
:*?C:&capcup;::⩇
:*?C:&capdot;::⩀
:*?C:&CapitalDifferentialD;::ⅅ
:*?C:&caps;::∩︀
:*?C:&caret;::⁁
:*?C:&caron;::ˇ
:*?C:&Cayleys;::ℭ
:*?C:&ccaps;::⩍
:*?C:&Ccaron;::Č
:*?C:&ccaron;::č
:*?C:&Ccedil;::Ç
:*?C:&ccedil;::ç
:*?C:&Ccirc;::Ĉ
:*?C:&ccirc;::ĉ
:*?C:&Cconint;::∰
:*?C:&ccups;::⩌
:*?C:&ccupssm;::⩐
:*?C:&Cdot;::Ċ
:*?C:&cdot;::ċ
:*?C:&cedil;::¸
:*?C:&Cedilla;::¸
:*?C:&cemptyv;::⦲
:*?C:&cent;::¢
:*?C:&CenterDot;::·
:*?C:&centerdot;::·
:*?C:&Cfr;::ℭ
:*?C:&cfr;::𝔠
:*?C:&CHcy;::Ч
:*?C:&chcy;::ч
:*?C:&check;::✓
:*?C:&checkmark;::✓
:*?C:&Chi;::Χ
:*?C:&chi;::χ
:*?C:&cir;::○
:*?C:&circ;::ˆ
:*?C:&circeq;::≗
:*?C:&circlearrowleft;::↺
:*?C:&circlearrowright;::↻
:*?C:&circledast;::⊛
:*?C:&circledcirc;::⊚
:*?C:&circleddash;::⊝
:*?C:&CircleDot;::⊙
:*?C:&circledR;::®
:*?C:&circledS;::Ⓢ
:*?C:&CircleMinus;::⊖
:*?C:&CirclePlus;::⊕
:*?C:&CircleTimes;::⊗
:*?C:&cirE;::⧃
:*?C:&cire;::≗
:*?C:&cirfnint;::⨐
:*?C:&cirmid;::⫯
:*?C:&cirscir;::⧂
:*?C:&ClockwiseContourIntegral;::∲
:*?C:&CloseCurlyDoubleQuote;::”
:*?C:&CloseCurlyQuote;::’
:*?C:&clubs;::♣
:*?C:&clubsuit;::♣
:*?C:&Colon;::∷
:*?C:&colon;:::
:*?C:&Colone;::⩴
:*?C:&colone;::≔
:*?C:&coloneq;::≔
:*?C:&comma;::""
:*?C:&commat;::@
:*?C:&comp;::∁
:*?C:&compfn;::∘
:*?C:&complement;::∁
:*?C:&complexes;::ℂ
:*?C:&cong;::≅
:*?C:&congdot;::⩭
:*?C:&Congruent;::≡
:*?C:&Conint;::∯
:*?C:&conint;::∮
:*?C:&ContourIntegral;::∮
:*?C:&Copf;::ℂ
:*?C:&copf;::𝕔
:*?C:&coprod;::∐
:*?C:&Coproduct;::∐
:*?C:&COPY;::©
:*?C:&copy;::©
:*?C:&copysr;::℗
:*?C:&CounterClockwiseContourIntegral;::∳
:*?C:&crarr;::↵
:*?C:&Cross;::⨯
:*?C:&cross;::✗
:*?C:&Cscr;::𝒞
:*?C:&cscr;::𝒸
:*?C:&csub;::⫏
:*?C:&csube;::⫑
:*?C:&csup;::⫐
:*?C:&csupe;::⫒
:*?C:&ctdot;::⋯
:*?C:&cudarrl;::⤸
:*?C:&cudarrr;::⤵
:*?C:&cuepr;::⋞
:*?C:&cuesc;::⋟
:*?C:&cularr;::↶
:*?C:&cularrp;::⤽
:*?C:&Cup;::⋓
:*?C:&cup;::∪
:*?C:&cupbrcap;::⩈
:*?C:&CupCap;::≍
:*?C:&cupcap;::⩆
:*?C:&cupcup;::⩊
:*?C:&cupdot;::⊍
:*?C:&cupor;::⩅
:*?C:&cups;::∪︀
:*?C:&curarr;::↷
:*?C:&curarrm;::⤼
:*?C:&curlyeqprec;::⋞
:*?C:&curlyeqsucc;::⋟
:*?C:&curlyvee;::⋎
:*?C:&curlywedge;::⋏
:*?C:&curren;::¤
:*?C:&curvearrowleft;::↶
:*?C:&curvearrowright;::↷
:*?C:&cuvee;::⋎
:*?C:&cuwed;::⋏
:*?C:&cwconint;::∲
:*?C:&cwint;::∱
:*?C:&cylcty;::⌭
:*?C:&Dagger;::‡
:*?C:&dagger;::†
:*?C:&daleth;::ℸ
:*?C:&Darr;::↡
:*?C:&dArr;::⇓
:*?C:&darr;::↓
:*?C:&dash;::‐
:*?C:&Dashv;::⫤
:*?C:&dashv;::⊣
:*?C:&dbkarow;::⤏
:*?C:&dblac;::˝
:*?C:&Dcaron;::Ď
:*?C:&dcaron;::ď
:*?C:&Dcy;::Д
:*?C:&dcy;::д
:*?C:&DD;::ⅅ
:*?C:&dd;::ⅆ
:*?C:&ddagger;::‡
:*?C:&ddarr;::⇊
:*?C:&DDotrahd;::⤑
:*?C:&ddotseq;::⩷
:*?C:&deg;::°
:*?C:&Del;::∇
:*?C:&Delta;::Δ
:*?C:&delta;::δ
:*?C:&demptyv;::⦱
:*?C:&dfisht;::⥿
:*?C:&Dfr;::𝔇
:*?C:&dfr;::𝔡
:*?C:&dHar;::⥥
:*?C:&dharl;::⇃
:*?C:&dharr;::⇂
:*?C:&DiacriticalAcute;::´
:*?C:&DiacriticalDot;::˙
:*?C:&DiacriticalDoubleAcute;::˝
:*?C:&DiacriticalGrave;::`
:*?C:&DiacriticalTilde;::˜
:*?C:&diam;::⋄
:*?C:&Diamond;::⋄
:*?C:&diamond;::⋄
:*?C:&diamondsuit;::♦
:*?C:&diams;::♦
:*?C:&die;::¨
:*?C:&DifferentialD;::ⅆ
:*?C:&digamma;::ϝ
:*?C:&disin;::⋲
:*?C:&div;::÷
:*?C:&divide;::÷
:*?C:&divideontimes;::⋇
:*?C:&divonx;::⋇
:*?C:&DJcy;::Ђ
:*?C:&djcy;::ђ
:*?C:&dlcorn;::⌞
:*?C:&dlcrop;::⌍
:*?C:&dollar;::$
:*?C:&Dopf;::𝔻
:*?C:&dopf;::𝕕
:*?C:&Dot;::¨
:*?C:&dot;::˙
:*?C:&DotDot;::⃜
:*?C:&doteq;::≐
:*?C:&doteqdot;::≑
:*?C:&DotEqual;::≐
:*?C:&dotminus;::∸
:*?C:&dotplus;::∔
:*?C:&dotsquare;::⊡
:*?C:&doublebarwedge;::⌆
:*?C:&DoubleContourIntegral;::∯
:*?C:&DoubleDot;::¨
:*?C:&DoubleDownArrow;::⇓
:*?C:&DoubleLeftArrow;::⇐
:*?C:&DoubleLeftRightArrow;::⇔
:*?C:&DoubleLeftTee;::⫤
:*?C:&DoubleLongLeftArrow;::⟸
:*?C:&DoubleLongLeftRightArrow;::⟺
:*?C:&DoubleLongRightArrow;::⟹
:*?C:&DoubleRightArrow;::⇒
:*?C:&DoubleRightTee;::⊨
:*?C:&DoubleUpArrow;::⇑
:*?C:&DoubleUpDownArrow;::⇕
:*?C:&DoubleVerticalBar;::∥
:*?C:&DownArrow;::↓
:*?C:&Downarrow;::⇓
:*?C:&downarrow;::↓
:*?C:&DownArrowBar;::⤓
:*?C:&DownArrowUpArrow;::⇵
:*?C:&DownBreve;::̑
:*?C:&downdownarrows;::⇊
:*?C:&downharpoonleft;::⇃
:*?C:&downharpoonright;::⇂
:*?C:&DownLeftRightVector;::⥐
:*?C:&DownLeftTeeVector;::⥞
:*?C:&DownLeftVector;::↽
:*?C:&DownLeftVectorBar;::⥖
:*?C:&DownRightTeeVector;::⥟
:*?C:&DownRightVector;::⇁
:*?C:&DownRightVectorBar;::⥗
:*?C:&DownTee;::⊤
:*?C:&DownTeeArrow;::↧
:*?C:&drbkarow;::⤐
:*?C:&drcorn;::⌟
:*?C:&drcrop;::⌌
:*?C:&Dscr;::𝒟
:*?C:&dscr;::𝒹
:*?C:&DScy;::Ѕ
:*?C:&dscy;::ѕ
:*?C:&dsol;::⧶
:*?C:&Dstrok;::Đ
:*?C:&dstrok;::đ
:*?C:&dtdot;::⋱
:*?C:&dtri;::▿
:*?C:&dtrif;::▾
:*?C:&duarr;::⇵
:*?C:&duhar;::⥯
:*?C:&dwangle;::⦦
:*?C:&DZcy;::Џ
:*?C:&dzcy;::џ
:*?C:&dzigrarr;::⟿
:*?C:&Eacute;::É
:*?C:&eacute;::é
:*?C:&easter;::⩮
:*?C:&Ecaron;::Ě
:*?C:&ecaron;::ě
:*?C:&ecir;::≖
:*?C:&Ecirc;::Ê
:*?C:&ecirc;::ê
:*?C:&ecolon;::≕
:*?C:&Ecy;::Э
:*?C:&ecy;::э
:*?C:&eDDot;::⩷
:*?C:&Edot;::Ė
:*?C:&eDot;::≑
:*?C:&edot;::ė
:*?C:&ee;::ⅇ
:*?C:&efDot;::≒
:*?C:&Efr;::𝔈
:*?C:&efr;::𝔢
:*?C:&eg;::⪚
:*?C:&Egrave;::È
:*?C:&egrave;::è
:*?C:&egs;::⪖
:*?C:&egsdot;::⪘
:*?C:&el;::⪙
:*?C:&Element;::∈
:*?C:&elinters;::⏧
:*?C:&ell;::ℓ
:*?C:&els;::⪕
:*?C:&elsdot;::⪗
:*?C:&Emacr;::Ē
:*?C:&emacr;::ē
:*?C:&empty;::∅
:*?C:&emptyset;::∅
:*?C:&EmptySmallSquare;::◻
:*?C:&emptyv;::∅
:*?C:&EmptyVerySmallSquare;::▫
:*?C:&emsp;::
:*?C:&emsp13;::
:*?C:&emsp14;::
:*?C:&ENG;::Ŋ
:*?C:&eng;::ŋ
:*?C:&ensp;::
:*?C:&Eogon;::Ę
:*?C:&eogon;::ę
:*?C:&Eopf;::𝔼
:*?C:&eopf;::𝕖
:*?C:&epar;::⋕
:*?C:&eparsl;::⧣
:*?C:&eplus;::⩱
:*?C:&epsi;::ε
:*?C:&Epsilon;::Ε
:*?C:&epsilon;::ε
:*?C:&epsiv;::ϵ
:*?C:&eqcirc;::≖
:*?C:&eqcolon;::≕
:*?C:&eqsim;::≂
:*?C:&eqslantgtr;::⪖
:*?C:&eqslantless;::⪕
:*?C:&Equal;::⩵
:*?C:&equals;::&ERROR!
:*?C:&EqualTilde;::≂
:*?C:&equest;::≟
:*?C:&Equilibrium;::⇌
:*?C:&equiv;::≡
:*?C:&equivDD;::⩸
:*?C:&eqvparsl;::⧥
:*?C:&erarr;::⥱
:*?C:&erDot;::≓
:*?C:&Escr;::ℰ
:*?C:&escr;::ℯ
:*?C:&esdot;::≐
:*?C:&Esim;::⩳
:*?C:&esim;::≂
:*?C:&Eta;::Η
:*?C:&eta;::η
:*?C:&ETH;::Ð
:*?C:&eth;::ð
:*?C:&Euml;::Ë
:*?C:&euml;::ë
:*?C:&euro;::€
:*?C:&excl;::!
:*?C:&exist;::∃
:*?C:&Exists;::∃
:*?C:&expectation;::ℰ
:*?C:&ExponentialE;::ⅇ
:*?C:&exponentiale;::ⅇ
:*?C:&fallingdotseq;::≒
:*?C:&Fcy;::Ф
:*?C:&fcy;::ф
:*?C:&female;::♀
:*?C:&ffilig;::ﬃ
:*?C:&fflig;::ﬀ
:*?C:&ffllig;::ﬄ
:*?C:&Ffr;::𝔉
:*?C:&ffr;::𝔣
:*?C:&filig;::ﬁ
:*?C:&FilledSmallSquare;::◼
:*?C:&FilledVerySmallSquare;::▪
:*?C:&fjlig;::fj
:*?C:&flat;::♭
:*?C:&fllig;::ﬂ
:*?C:&fltns;::▱
:*?C:&fnof;::ƒ
:*?C:&Fopf;::𝔽
:*?C:&fopf;::𝕗
:*?C:&ForAll;::∀
:*?C:&forall;::∀
:*?C:&fork;::⋔
:*?C:&forkv;::⫙
:*?C:&Fouriertrf;::ℱ
:*?C:&fpartint;::⨍
:*?C:&frac12;::½
:*?C:&frac13;::⅓
:*?C:&frac14;::¼
:*?C:&frac15;::⅕
:*?C:&frac16;::⅙
:*?C:&frac18;::⅛
:*?C:&frac23;::⅔
:*?C:&frac25;::⅖
:*?C:&frac34;::¾
:*?C:&frac35;::⅗
:*?C:&frac38;::⅜
:*?C:&frac45;::⅘
:*?C:&frac56;::⅚
:*?C:&frac58;::⅝
:*?C:&frac78;::⅞
:*?C:&frasl;::⁄
:*?C:&frown;::⌢
:*?C:&Fscr;::ℱ
:*?C:&fscr;::𝒻
:*?C:&gacute;::ǵ
:*?C:&Gamma;::Γ
:*?C:&gamma;::γ
:*?C:&Gammad;::Ϝ
:*?C:&gammad;::ϝ
:*?C:&gap;::⪆
:*?C:&Gbreve;::Ğ
:*?C:&gbreve;::ğ
:*?C:&Gcedil;::Ģ
:*?C:&Gcirc;::Ĝ
:*?C:&gcirc;::ĝ
:*?C:&Gcy;::Г
:*?C:&gcy;::г
:*?C:&Gdot;::Ġ
:*?C:&gdot;::ġ
:*?C:&gE;::≧
:*?C:&ge;::≥
:*?C:&gEl;::⪌
:*?C:&gel;::⋛
:*?C:&geq;::≥
:*?C:&geqq;::≧
:*?C:&geqslant;::⩾
:*?C:&ges;::⩾
:*?C:&gescc;::⪩
:*?C:&gesdot;::⪀
:*?C:&gesdoto;::⪂
:*?C:&gesdotol;::⪄
:*?C:&gesl;::⋛︀
:*?C:&gesles;::⪔
:*?C:&Gfr;::𝔊
:*?C:&gfr;::𝔤
:*?C:&Gg;::⋙
:*?C:&gg;::≫
:*?C:&ggg;::⋙
:*?C:&gimel;::ℷ
:*?C:&GJcy;::Ѓ
:*?C:&gjcy;::ѓ
:*?C:&gl;::≷
:*?C:&gla;::⪥
:*?C:&glE;::⪒
:*?C:&glj;::⪤
:*?C:&gnap;::⪊
:*?C:&gnapprox;::⪊
:*?C:&gnE;::≩
:*?C:&gne;::⪈
:*?C:&gneq;::⪈
:*?C:&gneqq;::≩
:*?C:&gnsim;::⋧
:*?C:&Gopf;::𝔾
:*?C:&gopf;::𝕘
:*?C:&grave;::`
:*?C:&GreaterEqual;::≥
:*?C:&GreaterEqualLess;::⋛
:*?C:&GreaterFullEqual;::≧
:*?C:&GreaterGreater;::⪢
:*?C:&GreaterLess;::≷
:*?C:&GreaterSlantEqual;::⩾
:*?C:&GreaterTilde;::≳
:*?C:&Gscr;::𝒢
:*?C:&gscr;::ℊ
:*?C:&gsim;::≳
:*?C:&gsime;::⪎
:*?C:&gsiml;::⪐
; :*?C:&GT;::>
:*?C:&Gt;::≫
; :*?C:&gt;::>
:*?C:&gtcc;::⪧
:*?C:&gtcir;::⩺
:*?C:&gtdot;::⋗
:*?C:&gtlPar;::⦕
:*?C:&gtquest;::⩼
:*?C:&gtrapprox;::⪆
:*?C:&gtrarr;::⥸
:*?C:&gtrdot;::⋗
:*?C:&gtreqless;::⋛
:*?C:&gtreqqless;::⪌
:*?C:&gtrless;::≷
:*?C:&gtrsim;::≳
:*?C:&gvertneqq;::≩︀
:*?C:&gvnE;::≩︀
:*?C:&Hacek;::ˇ
:*?C:&hairsp;::
:*?C:&half;::½
:*?C:&hamilt;::ℋ
:*?C:&HARDcy;::Ъ
:*?C:&hardcy;::ъ
:*?C:&hArr;::⇔
:*?C:&harr;::↔
:*?C:&harrcir;::⥈
:*?C:&harrw;::↭
:*?C:&Hat;::^
:*?C:&hbar;::ℏ
:*?C:&Hcirc;::Ĥ
:*?C:&hcirc;::ĥ
:*?C:&hearts;::♥
:*?C:&heartsuit;::♥
:*?C:&hellip;::…
:*?C:&hercon;::⊹
:*?C:&Hfr;::ℌ
:*?C:&hfr;::𝔥
:*?C:&HilbertSpace;::ℋ
:*?C:&hksearow;::⤥
:*?C:&hkswarow;::⤦
:*?C:&hoarr;::⇿
:*?C:&homtht;::∻
:*?C:&hookleftarrow;::↩
:*?C:&hookrightarrow;::↪
:*?C:&Hopf;::ℍ
:*?C:&hopf;::𝕙
:*?C:&horbar;::―
:*?C:&HorizontalLine;::─
:*?C:&Hscr;::ℋ
:*?C:&hscr;::𝒽
:*?C:&hslash;::ℏ
:*?C:&Hstrok;::Ħ
:*?C:&hstrok;::ħ
:*?C:&HumpDownHump;::≎
:*?C:&HumpEqual;::≏
:*?C:&hybull;::⁃
:*?C:&hyphen;::‐
:*?C:&Iacute;::Í
:*?C:&iacute;::í
:*?C:&ic;::⁣
:*?C:&Icirc;::Î
:*?C:&icirc;::î
:*?C:&Icy;::И
:*?C:&icy;::и
:*?C:&Idot;::İ
:*?C:&IEcy;::Е
:*?C:&iecy;::е
:*?C:&iexcl;::¡
:*?C:&iff;::⇔
:*?C:&Ifr;::ℑ
:*?C:&ifr;::𝔦
:*?C:&Igrave;::Ì
:*?C:&igrave;::ì
:*?C:&ii;::ⅈ
:*?C:&iiiint;::⨌
:*?C:&iiint;::∭
:*?C:&iinfin;::⧜
:*?C:&iiota;::℩
:*?C:&IJlig;::Ĳ
:*?C:&ijlig;::ĳ
:*?C:&Im;::ℑ
:*?C:&Imacr;::Ī
:*?C:&imacr;::ī
:*?C:&image;::ℑ
:*?C:&ImaginaryI;::ⅈ
:*?C:&imagline;::ℐ
:*?C:&imagpart;::ℑ
:*?C:&imath;::ı
:*?C:&imof;::⊷
:*?C:&imped;::Ƶ
:*?C:&Implies;::⇒
:*?C:&in;::∈
:*?C:&incare;::℅
:*?C:&infin;::∞
:*?C:&infintie;::⧝
:*?C:&inodot;::ı
:*?C:&Int;::∬
:*?C:&int;::∫
:*?C:&intcal;::⊺
:*?C:&integers;::ℤ
:*?C:&Integral;::∫
:*?C:&intercal;::⊺
:*?C:&Intersection;::⋂
:*?C:&intlarhk;::⨗
:*?C:&intprod;::⨼
:*?C:&InvisibleComma;::⁣
:*?C:&InvisibleTimes;::⁢
:*?C:&IOcy;::Ё
:*?C:&iocy;::ё
:*?C:&Iogon;::Į
:*?C:&iogon;::į
:*?C:&Iopf;::𝕀
:*?C:&iopf;::𝕚
:*?C:&Iota;::Ι
:*?C:&iota;::ι
:*?C:&iprod;::⨼
:*?C:&iquest;::¿
:*?C:&Iscr;::ℐ
:*?C:&iscr;::𝒾
:*?C:&isin;::∈
:*?C:&isindot;::⋵
:*?C:&isinE;::⋹
:*?C:&isins;::⋴
:*?C:&isinsv;::⋳
:*?C:&isinv;::∈
:*?C:&it;::⁢
:*?C:&Itilde;::Ĩ
:*?C:&itilde;::ĩ
:*?C:&Iukcy;::І
:*?C:&iukcy;::і
:*?C:&Iuml;::Ï
:*?C:&iuml;::ï
:*?C:&Jcirc;::Ĵ
:*?C:&jcirc;::ĵ
:*?C:&Jcy;::Й
:*?C:&jcy;::й
:*?C:&Jfr;::𝔍
:*?C:&jfr;::𝔧
:*?C:&jmath;::ȷ
:*?C:&Jopf;::𝕁
:*?C:&jopf;::𝕛
:*?C:&Jscr;::𝒥
:*?C:&jscr;::𝒿
:*?C:&Jsercy;::Ј
:*?C:&jsercy;::ј
:*?C:&Jukcy;::Є
:*?C:&jukcy;::є
:*?C:&Kappa;::Κ
:*?C:&kappa;::κ
:*?C:&kappav;::ϰ
:*?C:&Kcedil;::Ķ
:*?C:&kcedil;::ķ
:*?C:&Kcy;::К
:*?C:&kcy;::к
:*?C:&Kfr;::𝔎
:*?C:&kfr;::𝔨
:*?C:&kgreen;::ĸ
:*?C:&KHcy;::Х
:*?C:&khcy;::х
:*?C:&KJcy;::Ќ
:*?C:&kjcy;::ќ
:*?C:&Kopf;::𝕂
:*?C:&kopf;::𝕜
:*?C:&Kscr;::𝒦
:*?C:&kscr;::𝓀
:*?C:&lAarr;::⇚
:*?C:&Lacute;::Ĺ
:*?C:&lacute;::ĺ
:*?C:&laemptyv;::⦴
:*?C:&lagran;::ℒ
:*?C:&Lambda;::Λ
:*?C:&lambda;::λ
:*?C:&Lang;::⟪
:*?C:&lang;::⟨
:*?C:&langd;::⦑
:*?C:&langle;::⟨
:*?C:&lap;::⪅
:*?C:&Laplacetrf;::ℒ
:*?C:&laquo;::«
:*?C:&Larr;::↞
:*?C:&lArr;::⇐
:*?C:&larr;::←
:*?C:&larrb;::⇤
:*?C:&larrbfs;::⤟
:*?C:&larrfs;::⤝
:*?C:&larrhk;::↩
:*?C:&larrlp;::↫
:*?C:&larrpl;::⤹
:*?C:&larrsim;::⥳
:*?C:&larrtl;::↢
:*?C:&lat;::⪫
:*?C:&lAtail;::⤛
:*?C:&latail;::⤙
:*?C:&late;::⪭
:*?C:&lates;::⪭︀
:*?C:&lBarr;::⤎
:*?C:&lbarr;::⤌
:*?C:&lbbrk;::❲
:*?C:&lbrace;::{
:*?C:&lbrack;::[
:*?C:&lbrke;::⦋
:*?C:&lbrksld;::⦏
:*?C:&lbrkslu;::⦍
:*?C:&Lcaron;::Ľ
:*?C:&lcaron;::ľ
:*?C:&Lcedil;::Ļ
:*?C:&lcedil;::ļ
:*?C:&lceil;::⌈
:*?C:&lcub;::{
:*?C:&Lcy;::Л
:*?C:&lcy;::л
:*?C:&ldca;::⤶
:*?C:&ldquo;::“
:*?C:&ldquor;::„
:*?C:&ldrdhar;::⥧
:*?C:&ldrushar;::⥋
:*?C:&ldsh;::↲
:*?C:&lE;::≦
:*?C:&le;::≤
:*?C:&LeftAngleBracket;::⟨
:*?C:&LeftArrow;::←
:*?C:&Leftarrow;::⇐
:*?C:&leftarrow;::←
:*?C:&LeftArrowBar;::⇤
:*?C:&LeftArrowRightArrow;::⇆
:*?C:&leftarrowtail;::↢
:*?C:&LeftCeiling;::⌈
:*?C:&LeftDoubleBracket;::⟦
:*?C:&LeftDownTeeVector;::⥡
:*?C:&LeftDownVector;::⇃
:*?C:&LeftDownVectorBar;::⥙
:*?C:&LeftFloor;::⌊
:*?C:&leftharpoondown;::↽
:*?C:&leftharpoonup;::↼
:*?C:&leftleftarrows;::⇇
:*?C:&LeftRightArrow;::↔
:*?C:&Leftrightarrow;::⇔
:*?C:&leftrightarrow;::↔
:*?C:&leftrightarrows;::⇆
:*?C:&leftrightharpoons;::⇋
:*?C:&leftrightsquigarrow;::↭
:*?C:&LeftRightVector;::⥎
:*?C:&LeftTee;::⊣
:*?C:&LeftTeeArrow;::↤
:*?C:&LeftTeeVector;::⥚
:*?C:&leftthreetimes;::⋋
:*?C:&LeftTriangle;::⊲
:*?C:&LeftTriangleBar;::⧏
:*?C:&LeftTriangleEqual;::⊴
:*?C:&LeftUpDownVector;::⥑
:*?C:&LeftUpTeeVector;::⥠
:*?C:&LeftUpVector;::↿
:*?C:&LeftUpVectorBar;::⥘
:*?C:&LeftVector;::↼
:*?C:&LeftVectorBar;::⥒
:*?C:&lEg;::⪋
:*?C:&leg;::⋚
:*?C:&leq;::≤
:*?C:&leqq;::≦
:*?C:&leqslant;::⩽
:*?C:&les;::⩽
:*?C:&lescc;::⪨
:*?C:&lesdot;::⩿
:*?C:&lesdoto;::⪁
:*?C:&lesdotor;::⪃
:*?C:&lesg;::⋚︀
:*?C:&lesges;::⪓
:*?C:&lessapprox;::⪅
:*?C:&lessdot;::⋖
:*?C:&lesseqgtr;::⋚
:*?C:&lesseqqgtr;::⪋
:*?C:&LessEqualGreater;::⋚
:*?C:&LessFullEqual;::≦
:*?C:&LessGreater;::≶
:*?C:&lessgtr;::≶
:*?C:&LessLess;::⪡
:*?C:&lesssim;::≲
:*?C:&LessSlantEqual;::⩽
:*?C:&LessTilde;::≲
:*?C:&lfisht;::⥼
:*?C:&lfloor;::⌊
:*?C:&Lfr;::𝔏
:*?C:&lfr;::𝔩
:*?C:&lg;::≶
:*?C:&lgE;::⪑
:*?C:&lHar;::⥢
:*?C:&lhard;::↽
:*?C:&lharu;::↼
:*?C:&lharul;::⥪
:*?C:&lhblk;::▄
:*?C:&LJcy;::Љ
:*?C:&ljcy;::љ
:*?C:&Ll;::⋘
:*?C:&ll;::≪
:*?C:&llarr;::⇇
:*?C:&llcorner;::⌞
:*?C:&Lleftarrow;::⇚
:*?C:&llhard;::⥫
:*?C:&lltri;::◺
:*?C:&Lmidot;::Ŀ
:*?C:&lmidot;::ŀ
:*?C:&lmoust;::⎰
:*?C:&lmoustache;::⎰
:*?C:&lnap;::⪉
:*?C:&lnapprox;::⪉
:*?C:&lnE;::≨
:*?C:&lne;::⪇
:*?C:&lneq;::⪇
:*?C:&lneqq;::≨
:*?C:&lnsim;::⋦
:*?C:&loang;::⟬
:*?C:&loarr;::⇽
:*?C:&lobrk;::⟦
:*?C:&LongLeftArrow;::⟵
:*?C:&Longleftarrow;::⟸
:*?C:&longleftarrow;::⟵
:*?C:&LongLeftRightArrow;::⟷
:*?C:&Longleftrightarrow;::⟺
:*?C:&longleftrightarrow;::⟷
:*?C:&longmapsto;::⟼
:*?C:&LongRightArrow;::⟶
:*?C:&Longrightarrow;::⟹
:*?C:&longrightarrow;::⟶
:*?C:&looparrowleft;::↫
:*?C:&looparrowright;::↬
:*?C:&lopar;::⦅
:*?C:&Lopf;::𝕃
:*?C:&lopf;::𝕝
:*?C:&loplus;::⨭
:*?C:&lotimes;::⨴
:*?C:&lowast;::∗
:*?C:&lowbar;::_
:*?C:&LowerLeftArrow;::↙
:*?C:&LowerRightArrow;::↘
:*?C:&loz;::◊
:*?C:&lozenge;::◊
:*?C:&lozf;::⧫
:*?C:&lpar;::(
:*?C:&lparlt;::⦓
:*?C:&lrarr;::⇆
:*?C:&lrcorner;::⌟
:*?C:&lrhar;::⇋
:*?C:&lrhard;::⥭
:*?C:&lrm;::‎
:*?C:&lrtri;::⊿
:*?C:&lsaquo;::‹
:*?C:&Lscr;::ℒ
:*?C:&lscr;::𝓁
:*?C:&Lsh;::↰
:*?C:&lsh;::↰
:*?C:&lsim;::≲
:*?C:&lsime;::⪍
:*?C:&lsimg;::⪏
:*?C:&lsqb;::[
:*?C:&lsquo;::‘
:*?C:&lsquor;::‚
:*?C:&Lstrok;::Ł
:*?C:&lstrok;::ł
; :*?C:&LT;::<
:*?C:&Lt;::≪
; :*?C:&lt;::<
:*?C:&ltcc;::⪦
:*?C:&ltcir;::⩹
:*?C:&ltdot;::⋖
:*?C:&lthree;::⋋
:*?C:&ltimes;::⋉
:*?C:&ltlarr;::⥶
:*?C:&ltquest;::⩻
:*?C:&ltri;::◃
:*?C:&ltrie;::⊴
:*?C:&ltrif;::◂
:*?C:&ltrPar;::⦖
:*?C:&lurdshar;::⥊
:*?C:&luruhar;::⥦
:*?C:&lvertneqq;::≨︀
:*?C:&lvnE;::≨︀
:*?C:&macr;::¯
:*?C:&male;::♂
:*?C:&malt;::✠
:*?C:&maltese;::✠
:*?C:&Map;::⤅
:*?C:&map;::↦
:*?C:&mapsto;::↦
:*?C:&mapstodown;::↧
:*?C:&mapstoleft;::↤
:*?C:&mapstoup;::↥
:*?C:&marker;::▮
:*?C:&mcomma;::⨩
:*?C:&Mcy;::М
:*?C:&mcy;::м
:*?C:&mdash;::—
:*?C:&mDDot;::∺
:*?C:&measuredangle;::∡
:*?C:&MediumSpace;::
:*?C:&Mellintrf;::ℳ
:*?C:&Mfr;::𝔐
:*?C:&mfr;::𝔪
:*?C:&mho;::℧
:*?C:&micro;::µ
:*?C:&mid;::∣
:*?C:&midast;::*
:*?C:&midcir;::⫰
:*?C:&middot;::·
:*?C:&minus;::−
:*?C:&minusb;::⊟
:*?C:&minusd;::∸
:*?C:&minusdu;::⨪
:*?C:&MinusPlus;::∓
:*?C:&mlcp;::⫛
:*?C:&mldr;::…
:*?C:&mnplus;::∓
:*?C:&models;::⊧
:*?C:&Mopf;::𝕄
:*?C:&mopf;::𝕞
:*?C:&mp;::∓
:*?C:&Mscr;::ℳ
:*?C:&mscr;::𝓂
:*?C:&mstpos;::∾
:*?C:&Mu;::Μ
:*?C:&mu;::μ
:*?C:&multimap;::⊸
:*?C:&mumap;::⊸
:*?C:&nabla;::∇
:*?C:&Nacute;::Ń
:*?C:&nacute;::ń
:*?C:&nang;::∠⃒
:*?C:&nap;::≉
:*?C:&napE;::⩰̸
:*?C:&napid;::≋̸
:*?C:&napos;::ŉ
:*?C:&napprox;::≉
:*?C:&natur;::♮
:*?C:&natural;::♮
:*?C:&naturals;::ℕ
:*?C:&nbsp;:: 
:*?C:&nbump;::≎̸
:*?C:&nbumpe;::≏̸
:*?C:&ncap;::⩃
:*?C:&Ncaron;::Ň
:*?C:&ncaron;::ň
:*?C:&Ncedil;::Ņ
:*?C:&ncedil;::ņ
:*?C:&ncong;::≇
:*?C:&ncongdot;::⩭̸
:*?C:&ncup;::⩂
:*?C:&Ncy;::Н
:*?C:&ncy;::н
:*?C:&ndash;::–
:*?C:&ne;::≠
:*?C:&nearhk;::⤤
:*?C:&neArr;::⇗
:*?C:&nearr;::↗
:*?C:&nearrow;::↗
:*?C:&nedot;::≐̸
:*?C:&NegativeMediumSpace;::​
:*?C:&NegativeThickSpace;::​
:*?C:&NegativeThinSpace;::​
:*?C:&NegativeVeryThinSpace;::​
:*?C:&nequiv;::≢
:*?C:&nesear;::⤨
:*?C:&nesim;::≂̸
:*?C:&NestedGreaterGreater;::≫
:*?C:&NestedLessLess;::≪
:*?C:&NewLine;::
:*?C:&nexist;::∄
:*?C:&nexists;::∄
:*?C:&Nfr;::𝔑
:*?C:&nfr;::𝔫
:*?C:&ngE;::≧̸
:*?C:&nge;::≱
:*?C:&ngeq;::≱
:*?C:&ngeqq;::≧̸
:*?C:&ngeqslant;::⩾̸
:*?C:&nges;::⩾̸
:*?C:&nGg;::⋙̸
:*?C:&ngsim;::≵
:*?C:&nGt;::≫⃒
:*?C:&ngt;::≯
:*?C:&ngtr;::≯
:*?C:&nGtv;::≫̸
:*?C:&nhArr;::⇎
:*?C:&nharr;::↮
:*?C:&nhpar;::⫲
:*?C:&ni;::∋
:*?C:&nis;::⋼
:*?C:&nisd;::⋺
:*?C:&niv;::∋
:*?C:&NJcy;::Њ
:*?C:&njcy;::њ
:*?C:&nlArr;::⇍
:*?C:&nlarr;::↚
:*?C:&nldr;::‥
:*?C:&nlE;::≦̸
:*?C:&nle;::≰
:*?C:&nLeftarrow;::⇍
:*?C:&nleftarrow;::↚
:*?C:&nLeftrightarrow;::⇎
:*?C:&nleftrightarrow;::↮
:*?C:&nleq;::≰
:*?C:&nleqq;::≦̸
:*?C:&nleqslant;::⩽̸
:*?C:&nles;::⩽̸
:*?C:&nless;::≮
:*?C:&nLl;::⋘̸
:*?C:&nlsim;::≴
:*?C:&nLt;::≪⃒
:*?C:&nlt;::≮
:*?C:&nltri;::⋪
:*?C:&nltrie;::⋬
:*?C:&nLtv;::≪̸
:*?C:&nmid;::∤
:*?C:&NoBreak;::⁠
:*?C:&NonBreakingSpace;:: 
:*?C:&Nopf;::ℕ
:*?C:&nopf;::𝕟
:*?C:&Not;::⫬
:*?C:&not;::¬
:*?C:&NotCongruent;::≢
:*?C:&NotCupCap;::≭
:*?C:&NotDoubleVerticalBar;::∦
:*?C:&NotElement;::∉
:*?C:&NotEqual;::≠
:*?C:&NotEqualTilde;::≂̸
:*?C:&NotExists;::∄
:*?C:&NotGreater;::≯
:*?C:&NotGreaterEqual;::≱
:*?C:&NotGreaterFullEqual;::≧̸
:*?C:&NotGreaterGreater;::≫̸
:*?C:&NotGreaterLess;::≹
:*?C:&NotGreaterSlantEqual;::⩾̸
:*?C:&NotGreaterTilde;::≵
:*?C:&NotHumpDownHump;::≎̸
:*?C:&NotHumpEqual;::≏̸
:*?C:&notin;::∉
:*?C:&notindot;::⋵̸
:*?C:&notinE;::⋹̸
:*?C:&notinva;::∉
:*?C:&notinvb;::⋷
:*?C:&notinvc;::⋶
:*?C:&NotLeftTriangle;::⋪
:*?C:&NotLeftTriangleBar;::⧏̸
:*?C:&NotLeftTriangleEqual;::⋬
:*?C:&NotLess;::≮
:*?C:&NotLessEqual;::≰
:*?C:&NotLessGreater;::≸
:*?C:&NotLessLess;::≪̸
:*?C:&NotLessSlantEqual;::⩽̸
:*?C:&NotLessTilde;::≴
:*?C:&NotNestedGreaterGreater;::⪢̸
:*?C:&NotNestedLessLess;::⪡̸
:*?C:&notni;::∌
:*?C:&notniva;::∌
:*?C:&notnivb;::⋾
:*?C:&notnivc;::⋽
:*?C:&NotPrecedes;::⊀
:*?C:&NotPrecedesEqual;::⪯̸
:*?C:&NotPrecedesSlantEqual;::⋠
:*?C:&NotReverseElement;::∌
:*?C:&NotRightTriangle;::⋫
:*?C:&NotRightTriangleBar;::⧐̸
:*?C:&NotRightTriangleEqual;::⋭
:*?C:&NotSquareSubset;::⊏̸
:*?C:&NotSquareSubsetEqual;::⋢
:*?C:&NotSquareSuperset;::⊐̸
:*?C:&NotSquareSupersetEqual;::⋣
:*?C:&NotSubset;::⊂⃒
:*?C:&NotSubsetEqual;::⊈
:*?C:&NotSucceeds;::⊁
:*?C:&NotSucceedsEqual;::⪰̸
:*?C:&NotSucceedsSlantEqual;::⋡
:*?C:&NotSucceedsTilde;::≿̸
:*?C:&NotSuperset;::⊃⃒
:*?C:&NotSupersetEqual;::⊉
:*?C:&NotTilde;::≁
:*?C:&NotTildeEqual;::≄
:*?C:&NotTildeFullEqual;::≇
:*?C:&NotTildeTilde;::≉
:*?C:&NotVerticalBar;::∤
:*?C:&npar;::∦
:*?C:&nparallel;::∦
:*?C:&nparsl;::⫽⃥
:*?C:&npart;::∂̸
:*?C:&npolint;::⨔
:*?C:&npr;::⊀
:*?C:&nprcue;::⋠
:*?C:&npre;::⪯̸
:*?C:&nprec;::⊀
:*?C:&npreceq;::⪯̸
:*?C:&nrArr;::⇏
:*?C:&nrarr;::↛
:*?C:&nrarrc;::⤳̸
:*?C:&nrarrw;::↝̸
:*?C:&nRightarrow;::⇏
:*?C:&nrightarrow;::↛
:*?C:&nrtri;::⋫
:*?C:&nrtrie;::⋭
:*?C:&nsc;::⊁
:*?C:&nsccue;::⋡
:*?C:&nsce;::⪰̸
:*?C:&Nscr;::𝒩
:*?C:&nscr;::𝓃
:*?C:&nshortmid;::∤
:*?C:&nshortparallel;::∦
:*?C:&nsim;::≁
:*?C:&nsime;::≄
:*?C:&nsimeq;::≄
:*?C:&nsmid;::∤
:*?C:&nspar;::∦
:*?C:&nsqsube;::⋢
:*?C:&nsqsupe;::⋣
:*?C:&nsub;::⊄
:*?C:&nsubE;::⫅̸
:*?C:&nsube;::⊈
:*?C:&nsubset;::⊂⃒
:*?C:&nsubseteq;::⊈
:*?C:&nsubseteqq;::⫅̸
:*?C:&nsucc;::⊁
:*?C:&nsucceq;::⪰̸
:*?C:&nsup;::⊅
:*?C:&nsupE;::⫆̸
:*?C:&nsupe;::⊉
:*?C:&nsupset;::⊃⃒
:*?C:&nsupseteq;::⊉
:*?C:&nsupseteqq;::⫆̸
:*?C:&ntgl;::≹
:*?C:&Ntilde;::Ñ
:*?C:&ntilde;::ñ
:*?C:&ntlg;::≸
:*?C:&ntriangleleft;::⋪
:*?C:&ntrianglelefteq;::⋬
:*?C:&ntriangleright;::⋫
:*?C:&ntrianglerighteq;::⋭
:*?C:&Nu;::Ν
:*?C:&nu;::ν
:*?C:&num;::&
:*?C:&numero;::№
:*?C:&numsp;:: 
:*?C:&nvap;::≍⃒
:*?C:&nVDash;::⊯
:*?C:&nVdash;::⊮
:*?C:&nvDash;::⊭
:*?C:&nvdash;::⊬
:*?C:&nvge;::≥⃒
:*?C:&nvgt;::>⃒
:*?C:&nvHarr;::⤄
:*?C:&nvinfin;::⧞
:*?C:&nvlArr;::⤂
:*?C:&nvle;::≤⃒
:*?C:&nvlt;::<⃒
:*?C:&nvltrie;::⊴⃒
:*?C:&nvrArr;::⤃
:*?C:&nvrtrie;::⊵⃒
:*?C:&nvsim;::∼⃒
:*?C:&nwarhk;::⤣
:*?C:&nwArr;::⇖
:*?C:&nwarr;::↖
:*?C:&nwarrow;::↖
:*?C:&nwnear;::⤧
:*?C:&Oacute;::Ó
:*?C:&oacute;::ó
:*?C:&oast;::⊛
:*?C:&ocir;::⊚
:*?C:&Ocirc;::Ô
:*?C:&ocirc;::ô
:*?C:&Ocy;::О
:*?C:&ocy;::о
:*?C:&odash;::⊝
:*?C:&Odblac;::Ő
:*?C:&odblac;::ő
:*?C:&odiv;::⨸
:*?C:&odot;::⊙
:*?C:&odsold;::⦼
:*?C:&OElig;::Œ
:*?C:&oelig;::œ
:*?C:&ofcir;::⦿
:*?C:&Ofr;::𝔒
:*?C:&ofr;::𝔬
:*?C:&ogon;::˛
:*?C:&Ograve;::Ò
:*?C:&ograve;::ò
:*?C:&ogt;::⧁
:*?C:&ohbar;::⦵
:*?C:&ohm;::Ω
:*?C:&oint;::∮
:*?C:&olarr;::↺
:*?C:&olcir;::⦾
:*?C:&olcross;::⦻
:*?C:&oline;::‾
:*?C:&olt;::⧀
:*?C:&Omacr;::Ō
:*?C:&omacr;::ō
:*?C:&Omega;::Ω
:*?C:&omega;::ω
:*?C:&Omicron;::Ο
:*?C:&omicron;::ο
:*?C:&omid;::⦶
:*?C:&ominus;::⊖
:*?C:&Oopf;::𝕆
:*?C:&oopf;::𝕠
:*?C:&opar;::⦷
:*?C:&OpenCurlyDoubleQuote;::“
:*?C:&OpenCurlyQuote;::‘
:*?C:&operp;::⦹
:*?C:&oplus;::⊕
:*?C:&Or;::⩔
:*?C:&or;::∨
:*?C:&orarr;::↻
:*?C:&ord;::⩝
:*?C:&order;::ℴ
:*?C:&orderof;::ℴ
:*?C:&ordf;::ª
:*?C:&ordm;::º
:*?C:&origof;::⊶
:*?C:&oror;::⩖
:*?C:&orslope;::⩗
:*?C:&orv;::⩛
:*?C:&oS;::Ⓢ
:*?C:&Oscr;::𝒪
:*?C:&oscr;::ℴ
:*?C:&Oslash;::Ø
:*?C:&oslash;::ø
:*?C:&osol;::⊘
:*?C:&Otilde;::Õ
:*?C:&otilde;::õ
:*?C:&Otimes;::⨷
:*?C:&otimes;::⊗
:*?C:&otimesas;::⨶
:*?C:&Ouml;::Ö
:*?C:&ouml;::ö
:*?C:&ovbar;::⌽
:*?C:&OverBar;::‾
:*?C:&OverBrace;::⏞
:*?C:&OverBracket;::⎴
:*?C:&OverParenthesis;::⏜
:*?C:&par;::∥
:*?C:&para;::¶
:*?C:&parallel;::∥
:*?C:&parsim;::⫳
:*?C:&parsl;::⫽
:*?C:&part;::∂
:*?C:&PartialD;::∂
:*?C:&Pcy;::П
:*?C:&pcy;::п
:*?C:&percnt;::%
:*?C:&period;::.
:*?C:&permil;::‰
:*?C:&perp;::⊥
:*?C:&pertenk;::‱
:*?C:&Pfr;::𝔓
:*?C:&pfr;::𝔭
:*?C:&Phi;::Φ
:*?C:&phi;::φ
:*?C:&phiv;::ϕ
:*?C:&phmmat;::ℳ
:*?C:&phone;::☎
:*?C:&Pi;::Π
:*?C:&pi;::π
:*?C:&pitchfork;::⋔
:*?C:&piv;::ϖ
:*?C:&planck;::ℏ
:*?C:&planckh;::ℎ
:*?C:&plankv;::ℏ
:*?C:&plus;::+
:*?C:&plusacir;::⨣
:*?C:&plusb;::⊞
:*?C:&pluscir;::⨢
:*?C:&plusdo;::∔
:*?C:&plusdu;::⨥
:*?C:&pluse;::⩲
:*?C:&PlusMinus;::±
:*?C:&plusmn;::±
:*?C:&plussim;::⨦
:*?C:&plustwo;::⨧
:*?C:&pm;::±
:*?C:&Poincareplane;::ℌ
:*?C:&pointint;::⨕
:*?C:&Popf;::ℙ
:*?C:&popf;::𝕡
:*?C:&pound;::£
:*?C:&Pr;::⪻
:*?C:&pr;::≺
:*?C:&prap;::⪷
:*?C:&prcue;::≼
:*?C:&prE;::⪳
:*?C:&pre;::⪯
:*?C:&prec;::≺
:*?C:&precapprox;::⪷
:*?C:&preccurlyeq;::≼
:*?C:&Precedes;::≺
:*?C:&PrecedesEqual;::⪯
:*?C:&PrecedesSlantEqual;::≼
:*?C:&PrecedesTilde;::≾
:*?C:&preceq;::⪯
:*?C:&precnapprox;::⪹
:*?C:&precneqq;::⪵
:*?C:&precnsim;::⋨
:*?C:&precsim;::≾
:*?C:&Prime;::″
:*?C:&prime;::′
:*?C:&primes;::ℙ
:*?C:&prnap;::⪹
:*?C:&prnE;::⪵
:*?C:&prnsim;::⋨
:*?C:&prod;::∏
:*?C:&Product;::∏
:*?C:&profalar;::⌮
:*?C:&profline;::⌒
:*?C:&profsurf;::⌓
:*?C:&prop;::∝
:*?C:&Proportion;::∷
:*?C:&Proportional;::∝
:*?C:&propto;::∝
:*?C:&prsim;::≾
:*?C:&prurel;::⊰
:*?C:&Pscr;::𝒫
:*?C:&pscr;::𝓅
:*?C:&Psi;::Ψ
:*?C:&psi;::ψ
:*?C:&puncsp;::
:*?C:&Qfr;::𝔔
:*?C:&qfr;::𝔮
:*?C:&qint;::⨌
:*?C:&Qopf;::ℚ
:*?C:&qopf;::𝕢
:*?C:&qprime;::⁗
:*?C:&Qscr;::𝒬
:*?C:&qscr;::𝓆
:*?C:&quaternions;::ℍ
:*?C:&quatint;::⨖
:*?C:&quest;::?
:*?C:&questeq;::≟
; :*?C:&QUOT;::""""
; :*?C:&quot;::""""
:*?C:&rAarr;::⇛
:*?C:&race;::∽̱
:*?C:&Racute;::Ŕ
:*?C:&racute;::ŕ
:*?C:&radic;::√
:*?C:&raemptyv;::⦳
:*?C:&Rang;::⟫
:*?C:&rang;::⟩
:*?C:&rangd;::⦒
:*?C:&range;::⦥
:*?C:&rangle;::⟩
:*?C:&raquo;::»
:*?C:&Rarr;::↠
:*?C:&rArr;::⇒
:*?C:&rarr;::→
:*?C:&rarrap;::⥵
:*?C:&rarrb;::⇥
:*?C:&rarrbfs;::⤠
:*?C:&rarrc;::⤳
:*?C:&rarrfs;::⤞
:*?C:&rarrhk;::↪
:*?C:&rarrlp;::↬
:*?C:&rarrpl;::⥅
:*?C:&rarrsim;::⥴
:*?C:&Rarrtl;::⤖
:*?C:&rarrtl;::↣
:*?C:&rarrw;::↝
:*?C:&rAtail;::⤜
:*?C:&ratail;::⤚
:*?C:&ratio;::∶
:*?C:&rationals;::ℚ
:*?C:&RBarr;::⤐
:*?C:&rBarr;::⤏
:*?C:&rbarr;::⤍
:*?C:&rbbrk;::❳
:*?C:&rbrace;::}
:*?C:&rbrack;::]
:*?C:&rbrke;::⦌
:*?C:&rbrksld;::⦎
:*?C:&rbrkslu;::⦐
:*?C:&Rcaron;::Ř
:*?C:&rcaron;::ř
:*?C:&Rcedil;::Ŗ
:*?C:&rcedil;::ŗ
:*?C:&rceil;::⌉
:*?C:&rcub;::}
:*?C:&Rcy;::Р
:*?C:&rcy;::р
:*?C:&rdca;::⤷
:*?C:&rdldhar;::⥩
:*?C:&rdquo;::”
:*?C:&rdquor;::”
:*?C:&rdsh;::↳
:*?C:&Re;::ℜ
:*?C:&real;::ℜ
:*?C:&realine;::ℛ
:*?C:&realpart;::ℜ
:*?C:&reals;::ℝ
:*?C:&rect;::▭
:*?C:&REG;::®
:*?C:&reg;::®
:*?C:&ReverseElement;::∋
:*?C:&ReverseEquilibrium;::⇋
:*?C:&ReverseUpEquilibrium;::⥯
:*?C:&rfisht;::⥽
:*?C:&rfloor;::⌋
:*?C:&Rfr;::ℜ
:*?C:&rfr;::𝔯
:*?C:&rHar;::⥤
:*?C:&rhard;::⇁
:*?C:&rharu;::⇀
:*?C:&rharul;::⥬
:*?C:&Rho;::Ρ
:*?C:&rho;::ρ
:*?C:&rhov;::ϱ
:*?C:&RightAngleBracket;::⟩
:*?C:&RightArrow;::→
:*?C:&Rightarrow;::⇒
:*?C:&rightarrow;::→
:*?C:&RightArrowBar;::⇥
:*?C:&RightArrowLeftArrow;::⇄
:*?C:&rightarrowtail;::↣
:*?C:&RightCeiling;::⌉
:*?C:&RightDoubleBracket;::⟧
:*?C:&RightDownTeeVector;::⥝
:*?C:&RightDownVector;::⇂
:*?C:&RightDownVectorBar;::⥕
:*?C:&RightFloor;::⌋
:*?C:&rightharpoondown;::⇁
:*?C:&rightharpoonup;::⇀
:*?C:&rightleftarrows;::⇄
:*?C:&rightleftharpoons;::⇌
:*?C:&rightrightarrows;::⇉
:*?C:&rightsquigarrow;::↝
:*?C:&RightTee;::⊢
:*?C:&RightTeeArrow;::↦
:*?C:&RightTeeVector;::⥛
:*?C:&rightthreetimes;::⋌
:*?C:&RightTriangle;::⊳
:*?C:&RightTriangleBar;::⧐
:*?C:&RightTriangleEqual;::⊵
:*?C:&RightUpDownVector;::⥏
:*?C:&RightUpTeeVector;::⥜
:*?C:&RightUpVector;::↾
:*?C:&RightUpVectorBar;::⥔
:*?C:&RightVector;::⇀
:*?C:&RightVectorBar;::⥓
:*?C:&ring;::˚
:*?C:&risingdotseq;::≓
:*?C:&rlarr;::⇄
:*?C:&rlhar;::⇌
:*?C:&rlm;::‏
:*?C:&rmoust;::⎱
:*?C:&rmoustache;::⎱
:*?C:&rnmid;::⫮
:*?C:&roang;::⟭
:*?C:&roarr;::⇾
:*?C:&robrk;::⟧
:*?C:&ropar;::⦆
:*?C:&Ropf;::ℝ
:*?C:&ropf;::𝕣
:*?C:&roplus;::⨮
:*?C:&rotimes;::⨵
:*?C:&RoundImplies;::⥰
:*?C:&rpar;::)
:*?C:&rpargt;::⦔
:*?C:&rppolint;::⨒
:*?C:&rrarr;::⇉
:*?C:&Rrightarrow;::⇛
:*?C:&rsaquo;::›
:*?C:&Rscr;::ℛ
:*?C:&rscr;::𝓇
:*?C:&Rsh;::↱
:*?C:&rsh;::↱
:*?C:&rsqb;::]
:*?C:&rsquo;::’
:*?C:&rsquor;::’
:*?C:&rthree;::⋌
:*?C:&rtimes;::⋊
:*?C:&rtri;::▹
:*?C:&rtrie;::⊵
:*?C:&rtrif;::▸
:*?C:&rtriltri;::⧎
:*?C:&RuleDelayed;::⧴
:*?C:&ruluhar;::⥨
:*?C:&rx;::℞
:*?C:&Sacute;::Ś
:*?C:&sacute;::ś
:*?C:&sbquo;::‚
:*?C:&Sc;::⪼
:*?C:&sc;::≻
:*?C:&scap;::⪸
:*?C:&Scaron;::Š
:*?C:&scaron;::š
:*?C:&sccue;::≽
:*?C:&scE;::⪴
:*?C:&sce;::⪰
:*?C:&Scedil;::Ş
:*?C:&scedil;::ş
:*?C:&Scirc;::Ŝ
:*?C:&scirc;::ŝ
:*?C:&scnap;::⪺
:*?C:&scnE;::⪶
:*?C:&scnsim;::⋩
:*?C:&scpolint;::⨓
:*?C:&scsim;::≿
:*?C:&Scy;::С
:*?C:&scy;::с
:*?C:&sdot;::⋅
:*?C:&sdotb;::⊡
:*?C:&sdote;::⩦
:*?C:&searhk;::⤥
:*?C:&seArr;::⇘
:*?C:&searr;::↘
:*?C:&searrow;::↘
:*?C:&sect;::§
:*?C:&semi;::;
:*?C:&seswar;::⤩
:*?C:&setminus;::∖
:*?C:&setmn;::∖
:*?C:&sext;::✶
:*?C:&Sfr;::𝔖
:*?C:&sfr;::𝔰
:*?C:&sfrown;::⌢
:*?C:&sharp;::♯
:*?C:&SHCHcy;::Щ
:*?C:&shchcy;::щ
:*?C:&SHcy;::Ш
:*?C:&shcy;::ш
:*?C:&ShortDownArrow;::↓
:*?C:&ShortLeftArrow;::←
:*?C:&shortmid;::∣
:*?C:&shortparallel;::∥
:*?C:&ShortRightArrow;::→
:*?C:&ShortUpArrow;::↑
:*?C:&shy;::­
:*?C:&Sigma;::Σ
:*?C:&sigma;::σ
:*?C:&sigmaf;::ς
:*?C:&sigmav;::ς
:*?C:&sim;::∼
:*?C:&simdot;::⩪
:*?C:&sime;::≃
:*?C:&simeq;::≃
:*?C:&simg;::⪞
:*?C:&simgE;::⪠
:*?C:&siml;::⪝
:*?C:&simlE;::⪟
:*?C:&simne;::≆
:*?C:&simplus;::⨤
:*?C:&simrarr;::⥲
:*?C:&slarr;::←
:*?C:&SmallCircle;::∘
:*?C:&smallsetminus;::∖
:*?C:&smashp;::⨳
:*?C:&smeparsl;::⧤
:*?C:&smid;::∣
:*?C:&smile;::⌣
:*?C:&smt;::⪪
:*?C:&smte;::⪬
:*?C:&smtes;::⪬︀
:*?C:&SOFTcy;::Ь
:*?C:&softcy;::ь
:*?C:&sol;::/
:*?C:&solb;::⧄
:*?C:&solbar;::⌿
:*?C:&Sopf;::𝕊
:*?C:&sopf;::𝕤
:*?C:&spades;::♠
:*?C:&spadesuit;::♠
:*?C:&spar;::∥
:*?C:&sqcap;::⊓
:*?C:&sqcaps;::⊓︀
:*?C:&sqcup;::⊔
:*?C:&sqcups;::⊔︀
:*?C:&Sqrt;::√
:*?C:&sqsub;::⊏
:*?C:&sqsube;::⊑
:*?C:&sqsubset;::⊏
:*?C:&sqsubseteq;::⊑
:*?C:&sqsup;::⊐
:*?C:&sqsupe;::⊒
:*?C:&sqsupset;::⊐
:*?C:&sqsupseteq;::⊒
:*?C:&squ;::□
:*?C:&Square;::□
:*?C:&square;::□
:*?C:&SquareIntersection;::⊓
:*?C:&SquareSubset;::⊏
:*?C:&SquareSubsetEqual;::⊑
:*?C:&SquareSuperset;::⊐
:*?C:&SquareSupersetEqual;::⊒
:*?C:&SquareUnion;::⊔
:*?C:&squarf;::▪
:*?C:&squf;::▪
:*?C:&srarr;::→
:*?C:&Sscr;::𝒮
:*?C:&sscr;::𝓈
:*?C:&ssetmn;::∖
:*?C:&ssmile;::⌣
:*?C:&sstarf;::⋆
:*?C:&Star;::⋆
:*?C:&star;::☆
:*?C:&starf;::★
:*?C:&straightepsilon;::ϵ
:*?C:&straightphi;::ϕ
:*?C:&strns;::¯
:*?C:&Sub;::⋐
:*?C:&sub;::⊂
:*?C:&subdot;::⪽
:*?C:&subE;::⫅
:*?C:&sube;::⊆
:*?C:&subedot;::⫃
:*?C:&submult;::⫁
:*?C:&subnE;::⫋
:*?C:&subne;::⊊
:*?C:&subplus;::⪿
:*?C:&subrarr;::⥹
:*?C:&Subset;::⋐
:*?C:&subset;::⊂
:*?C:&subseteq;::⊆
:*?C:&subseteqq;::⫅
:*?C:&SubsetEqual;::⊆
:*?C:&subsetneq;::⊊
:*?C:&subsetneqq;::⫋
:*?C:&subsim;::⫇
:*?C:&subsub;::⫕
:*?C:&subsup;::⫓
:*?C:&succ;::≻
:*?C:&succapprox;::⪸
:*?C:&succcurlyeq;::≽
:*?C:&Succeeds;::≻
:*?C:&SucceedsEqual;::⪰
:*?C:&SucceedsSlantEqual;::≽
:*?C:&SucceedsTilde;::≿
:*?C:&succeq;::⪰
:*?C:&succnapprox;::⪺
:*?C:&succneqq;::⪶
:*?C:&succnsim;::⋩
:*?C:&succsim;::≿
:*?C:&SuchThat;::∋
:*?C:&Sum;::∑
:*?C:&sum;::∑
:*?C:&sung;::♪
:*?C:&Sup;::⋑
:*?C:&sup;::⊃
:*?C:&sup1;::¹
:*?C:&sup2;::²
:*?C:&sup3;::³
:*?C:&supdot;::⪾
:*?C:&supdsub;::⫘
:*?C:&supE;::⫆
:*?C:&supe;::⊇
:*?C:&supedot;::⫄
:*?C:&Superset;::⊃
:*?C:&SupersetEqual;::⊇
:*?C:&suphsol;::⟉
:*?C:&suphsub;::⫗
:*?C:&suplarr;::⥻
:*?C:&supmult;::⫂
:*?C:&supnE;::⫌
:*?C:&supne;::⊋
:*?C:&supplus;::⫀
:*?C:&Supset;::⋑
:*?C:&supset;::⊃
:*?C:&supseteq;::⊇
:*?C:&supseteqq;::⫆
:*?C:&supsetneq;::⊋
:*?C:&supsetneqq;::⫌
:*?C:&supsim;::⫈
:*?C:&supsub;::⫔
:*?C:&supsup;::⫖
:*?C:&swarhk;::⤦
:*?C:&swArr;::⇙
:*?C:&swarr;::↙
:*?C:&swarrow;::↙
:*?C:&swnwar;::⤪
:*?C:&szlig;::ß
:*?C:&Tab;::
:*?C:&target;::⌖
:*?C:&Tau;::Τ
:*?C:&tau;::τ
:*?C:&tbrk;::⎴
:*?C:&Tcaron;::Ť
:*?C:&tcaron;::ť
:*?C:&Tcedil;::Ţ
:*?C:&tcedil;::ţ
:*?C:&Tcy;::Т
:*?C:&tcy;::т
:*?C:&tdot;::⃛
:*?C:&telrec;::⌕
:*?C:&Tfr;::𝔗
:*?C:&tfr;::𝔱
:*?C:&there4;::∴
:*?C:&Therefore;::∴
:*?C:&therefore;::∴
:*?C:&Theta;::Θ
:*?C:&theta;::θ
:*?C:&thetasym;::ϑ
:*?C:&thetav;::ϑ
:*?C:&thickapprox;::≈
:*?C:&thicksim;::∼
:*?C:&ThickSpace;::
:*?C:&thinsp;::
:*?C:&ThinSpace;::
:*?C:&thkap;::≈
:*?C:&thksim;::∼
:*?C:&THORN;::Þ
:*?C:&thorn;::þ
:*?C:&Tilde;::∼
:*?C:&tilde;::˜
:*?C:&TildeEqual;::≃
:*?C:&TildeFullEqual;::≅
:*?C:&TildeTilde;::≈
:*?C:&times;::×
:*?C:&timesb;::⊠
:*?C:&timesbar;::⨱
:*?C:&timesd;::⨰
:*?C:&tint;::∭
:*?C:&toea;::⤨
:*?C:&top;::⊤
:*?C:&topbot;::⌶
:*?C:&topcir;::⫱
:*?C:&Topf;::𝕋
:*?C:&topf;::𝕥
:*?C:&topfork;::⫚
:*?C:&tosa;::⤩
:*?C:&tprime;::‴
:*?C:&TRADE;::™
:*?C:&trade;::™
:*?C:&triangle;::▵
:*?C:&triangledown;::▿
:*?C:&triangleleft;::◃
:*?C:&trianglelefteq;::⊴
:*?C:&triangleq;::≜
:*?C:&triangleright;::▹
:*?C:&trianglerighteq;::⊵
:*?C:&tridot;::◬
:*?C:&trie;::≜
:*?C:&triminus;::⨺
:*?C:&TripleDot;::⃛
:*?C:&triplus;::⨹
:*?C:&trisb;::⧍
:*?C:&tritime;::⨻
:*?C:&trpezium;::⏢
:*?C:&Tscr;::𝒯
:*?C:&tscr;::𝓉
:*?C:&TScy;::Ц
:*?C:&tscy;::ц
:*?C:&TSHcy;::Ћ
:*?C:&tshcy;::ћ
:*?C:&Tstrok;::Ŧ
:*?C:&tstrok;::ŧ
:*?C:&twixt;::≬
:*?C:&twoheadleftarrow;::↞
:*?C:&twoheadrightarrow;::↠
:*?C:&Uacute;::Ú
:*?C:&uacute;::ú
:*?C:&Uarr;::↟
:*?C:&uArr;::⇑
:*?C:&uarr;::↑
:*?C:&Uarrocir;::⥉
:*?C:&Ubrcy;::Ў
:*?C:&ubrcy;::ў
:*?C:&Ubreve;::Ŭ
:*?C:&ubreve;::ŭ
:*?C:&Ucirc;::Û
:*?C:&ucirc;::û
:*?C:&Ucy;::У
:*?C:&ucy;::у
:*?C:&udarr;::⇅
:*?C:&Udblac;::Ű
:*?C:&udblac;::ű
:*?C:&udhar;::⥮
:*?C:&ufisht;::⥾
:*?C:&Ufr;::𝔘
:*?C:&ufr;::𝔲
:*?C:&Ugrave;::Ù
:*?C:&ugrave;::ù
:*?C:&uHar;::⥣
:*?C:&uharl;::↿
:*?C:&uharr;::↾
:*?C:&uhblk;::▀
:*?C:&ulcorn;::⌜
:*?C:&ulcorner;::⌜
:*?C:&ulcrop;::⌏
:*?C:&ultri;::◸
:*?C:&Umacr;::Ū
:*?C:&umacr;::ū
:*?C:&uml;::¨
:*?C:&UnderBar;::_
:*?C:&UnderBrace;::⏟
:*?C:&UnderBracket;::⎵
:*?C:&UnderParenthesis;::⏝
:*?C:&Union;::⋃
:*?C:&UnionPlus;::⊎
:*?C:&Uogon;::Ų
:*?C:&uogon;::ų
:*?C:&Uopf;::𝕌
:*?C:&uopf;::𝕦
:*?C:&UpArrow;::↑
:*?C:&Uparrow;::⇑
:*?C:&uparrow;::↑
:*?C:&UpArrowBar;::⤒
:*?C:&UpArrowDownArrow;::⇅
:*?C:&UpDownArrow;::↕
:*?C:&Updownarrow;::⇕
:*?C:&updownarrow;::↕
:*?C:&UpEquilibrium;::⥮
:*?C:&upharpoonleft;::↿
:*?C:&upharpoonright;::↾
:*?C:&uplus;::⊎
:*?C:&UpperLeftArrow;::↖
:*?C:&UpperRightArrow;::↗
:*?C:&Upsi;::ϒ
:*?C:&upsi;::υ
:*?C:&upsih;::ϒ
:*?C:&Upsilon;::Υ
:*?C:&upsilon;::υ
:*?C:&UpTee;::⊥
:*?C:&UpTeeArrow;::↥
:*?C:&upuparrows;::⇈
:*?C:&urcorn;::⌝
:*?C:&urcorner;::⌝
:*?C:&urcrop;::⌎
:*?C:&Uring;::Ů
:*?C:&uring;::ů
:*?C:&urtri;::◹
:*?C:&Uscr;::𝒰
:*?C:&uscr;::𝓊
:*?C:&utdot;::⋰
:*?C:&Utilde;::Ũ
:*?C:&utilde;::ũ
:*?C:&utri;::▵
:*?C:&utrif;::▴
:*?C:&uuarr;::⇈
:*?C:&Uuml;::Ü
:*?C:&uuml;::ü
:*?C:&uwangle;::⦧
:*?C:&vangrt;::⦜
:*?C:&varepsilon;::ϵ
:*?C:&varkappa;::ϰ
:*?C:&varnothing;::∅
:*?C:&varphi;::ϕ
:*?C:&varpi;::ϖ
:*?C:&varpropto;::∝
:*?C:&vArr;::⇕
:*?C:&varr;::↕
:*?C:&varrho;::ϱ
:*?C:&varsigma;::ς
:*?C:&varsubsetneq;::⊊︀
:*?C:&varsubsetneqq;::⫋︀
:*?C:&varsupsetneq;::⊋︀
:*?C:&varsupsetneqq;::⫌︀
:*?C:&vartheta;::ϑ
:*?C:&vartriangleleft;::⊲
:*?C:&vartriangleright;::⊳
:*?C:&Vbar;::⫫
:*?C:&vBar;::⫨
:*?C:&vBarv;::⫩
:*?C:&Vcy;::В
:*?C:&vcy;::в
:*?C:&VDash;::⊫
:*?C:&Vdash;::⊩
:*?C:&vDash;::⊨
:*?C:&vdash;::⊢
:*?C:&Vdashl;::⫦
:*?C:&Vee;::⋁
:*?C:&vee;::∨
:*?C:&veebar;::⊻
:*?C:&veeeq;::≚
:*?C:&vellip;::⋮
:*?C:&Verbar;::‖
:*?C:&verbar;::|
:*?C:&Vert;::‖
:*?C:&vert;::|
:*?C:&VerticalBar;::∣
:*?C:&VerticalLine;::|
:*?C:&VerticalSeparator;::❘
:*?C:&VerticalTilde;::≀
:*?C:&VeryThinSpace;::
:*?C:&Vfr;::𝔙
:*?C:&vfr;::𝔳
:*?C:&vltri;::⊲
:*?C:&vnsub;::⊂⃒
:*?C:&vnsup;::⊃⃒
:*?C:&Vopf;::𝕍
:*?C:&vopf;::𝕧
:*?C:&vprop;::∝
:*?C:&vrtri;::⊳
:*?C:&Vscr;::𝒱
:*?C:&vscr;::𝓋
:*?C:&vsubnE;::⫋︀
:*?C:&vsubne;::⊊︀
:*?C:&vsupnE;::⫌︀
:*?C:&vsupne;::⊋︀
:*?C:&Vvdash;::⊪
:*?C:&vzigzag;::⦚
:*?C:&Wcirc;::Ŵ
:*?C:&wcirc;::ŵ
:*?C:&wedbar;::⩟
:*?C:&Wedge;::⋀
:*?C:&wedge;::∧
:*?C:&wedgeq;::≙
:*?C:&weierp;::℘
:*?C:&Wfr;::𝔚
:*?C:&wfr;::𝔴
:*?C:&Wopf;::𝕎
:*?C:&wopf;::𝕨
:*?C:&wp;::℘
:*?C:&wr;::≀
:*?C:&wreath;::≀
:*?C:&Wscr;::𝒲
:*?C:&wscr;::𝓌
:*?C:&xcap;::⋂
:*?C:&xcirc;::◯
:*?C:&xcup;::⋃
:*?C:&xdtri;::▽
:*?C:&Xfr;::𝔛
:*?C:&xfr;::𝔵
:*?C:&xhArr;::⟺
:*?C:&xharr;::⟷
:*?C:&Xi;::Ξ
:*?C:&xi;::ξ
:*?C:&xlArr;::⟸
:*?C:&xlarr;::⟵
:*?C:&xmap;::⟼
:*?C:&xnis;::⋻
:*?C:&xodot;::⨀
:*?C:&Xopf;::𝕏
:*?C:&xopf;::𝕩
:*?C:&xoplus;::⨁
:*?C:&xotime;::⨂
:*?C:&xrArr;::⟹
:*?C:&xrarr;::⟶
:*?C:&Xscr;::𝒳
:*?C:&xscr;::𝓍
:*?C:&xsqcup;::⨆
:*?C:&xuplus;::⨄
:*?C:&xutri;::△
:*?C:&xvee;::⋁
:*?C:&xwedge;::⋀
:*?C:&Yacute;::Ý
:*?C:&yacute;::ý
:*?C:&YAcy;::Я
:*?C:&yacy;::я
:*?C:&Ycirc;::Ŷ
:*?C:&ycirc;::ŷ
:*?C:&Ycy;::Ы
:*?C:&ycy;::ы
:*?C:&yen;::¥
:*?C:&Yfr;::𝔜
:*?C:&yfr;::𝔶
:*?C:&YIcy;::Ї
:*?C:&yicy;::ї
:*?C:&Yopf;::𝕐
:*?C:&yopf;::𝕪
:*?C:&Yscr;::𝒴
:*?C:&yscr;::𝓎
:*?C:&YUcy;::Ю
:*?C:&yucy;::ю
:*?C:&Yuml;::Ÿ
:*?C:&yuml;::ÿ
:*?C:&Zacute;::Ź
:*?C:&zacute;::ź
:*?C:&Zcaron;::Ž
:*?C:&zcaron;::ž
:*?C:&Zcy;::З
:*?C:&zcy;::з
:*?C:&Zdot;::Ż
:*?C:&zdot;::ż
:*?C:&zeetrf;::ℨ
:*?C:&ZeroWidthSpace;::​
:*?C:&Zeta;::Ζ
:*?C:&zeta;::ζ
:*?C:&Zfr;::ℨ
:*?C:&zfr;::𝔷
:*?C:&ZHcy;::Ж
:*?C:&zhcy;::ж
:*?C:&zigrarr;::⇝
:*?C:&Zopf;::ℤ
:*?C:&zopf;::𝕫
:*?C:&Zscr;::𝒵
:*?C:&zscr;::𝓏
:*?C:&zwj;::‍
:*?C:&zwnj;::‌
